### ISSUE TITLE
🐛 [BUG] - Planks dates in historic don't match the day of the exercise

### ISSUE THREAD

**Issue by TheSecondWing** [madmustachecompany/Blast-Workout-App#74]
### Description

Hello,

It seems that some exercises dates in the historic do not match the date of the execution of the exercise.

For example, in my planks historic I have the date of 10th of January displayed three times while I actually did the exercise on the 11th, 12th and 13th of January.

Hint: I actually prepare the sessions in the app a few days in avance, and put them in the workouts queue. And I think I prepared the three sessions the 10th of January, so that's why the dates might match this one.

I've only seen this for planks actually.

Thanks.

### Reproduction steps

```bash
1. Go to '...'
2. Tap on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

None

**Comment by TheSecondWing** [comment]
![Screenshot_20240129-125834](https://github.com/madmustachecompany/Blast-Workout-App/assets/156791196/2a3f64af-9de6-4747-be99-f878b2cc154d)

**Comment by TheSecondWing** [comment]
![Screenshot_20240129-125839](https://github.com/madmustachecompany/Blast-Workout-App/assets/156791196/912fba5b-6ccc-4230-801a-a49eddc01f7e)

**Comment by madmustachecompany** [comment]
Hi @TheSecondWing,

Thanks for your bug report which, as you mentioned, shows the creation date and not the actual execution date.
We've also noticed this problem in recent fixes, and it should be resolved in the latest version (1.61), which has just been released.
Please let us know if this is the case or if you are still experiencing the same issue.

**Comment by TheSecondWing** [comment]
Hello @madmustachecompany.

The problem still exists in the newest version I just downloaded.

![Screenshot_20240130-083000.jpg](https://github.com/madmustachecompany/Blast-Workout-App/assets/156791196/9d82fa08-2354-4c6a-bef2-fbfa719d3a8a)

![Screenshot_20240130-082957.jpg](https://github.com/madmustachecompany/Blast-Workout-App/assets/156791196/4ebb68ad-b5b7-49ba-bc79-af931002042e)

![Screenshot_20240130-082954.jpg](https://github.com/madmustachecompany/Blast-Workout-App/assets/156791196/998d0c97-66d4-44c0-9c87-9280d4ae49f0)

**Comment by madmustachecompany** [comment]
Indeed,
I thought that had been sorted (as it also affected the cardio exercises), sorry for the mix-up :/
The fix will be added in the next update, thanks for reporting it.

**Comment by TheSecondWing** [comment]
> Indeed,
> I thought that had been sorted (as it also affected the cardio exercises), sorry for the mix-up :/
> The fix will be added in the next update, thanks for reporting it.

No problem, thanks a lot!

**Comment by madmustachecompany** [comment]
Hi @TheSecondWing,
We have released an update (v1.61.2) which should have corrected this issue. Can you confirm it?
Thanks

**Comment by TheSecondWing** [comment]
Hi @madmustachecompany,
Problem sorted. The date now matches the execution date. Perfect. Thanks!
Ticket can be closed.
